name: Deploy to EC2

on:
  push:
    branches:
      - main  # Replace with your default branch if different

jobs:
  deploy:
    name: Deploy to EC2 via SSH
    runs-on: ubuntu-latest
    environment: production  # Replace with your environment name

    steps:
      - name: Checkout code (optional)
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: ${{ secrets.EC2_HOST }}

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            cd /var/www/html &&
            git pull origin main
          '
